###  Erasmo Cardoso

version: '3.8'

services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"  
    volumes:
      - ./backend:/usr/src/app  
    depends_on:
      - mysql  
      - elasticsearch
    environment:
      DB_HOST: mysql  
      DB_USER: erasmo  
      DB_PASSWORD: 3727  
      DB_NAME: chat  
      ELASTIC_HOST: http://backend_elasticsearch:9200
    networks:
      - app_network

  mysql:
    image: mysql:8.0  
    container_name: backend_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3727  
      MYSQL_USER: erasmo  
      MYSQL_PASSWORD: 3727  
      MYSQL_DATABASE: chat  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app_network

  elasticsearch:
    build:
      context: .  
      dockerfile: elastic/Dockerfile
    container_name: backend_elasticsearch
    restart: always
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend_elasticsearch:9200"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
